---
title: "Project1"
author: "Ajay Tripathi"
date: "April 28, 2018"
output: html_document
---
```{r pa1, echo=TRUE}
activity<-read.csv("./activity.csv",header = TRUE)
activity[,2]<-as.Date(activity$date)
```
```{r pa2, echo=TRUE}
str(activity)
```
```{r pa3, echo=TRUE}
steps_1<-with(activity,tapply(steps,date,sum,na.rm=TRUE))
hist(steps_1,col = "green",xlab = "Total Steps",ylab = "Frequency",main = "Total Number of Steps per Day")
```
```{r pa4, echo=TRUE}
print(mean_steps<-mean(steps_1))
print(median_steps<-median(steps_1))
summary(steps_1)
```
```{r=pa5, echo=TRUE}
avg_steps<-with(activity,tapply(steps,interval,mean,na.rm=TRUE))
intervals<-unique(activity$interval)
new<-data.frame(cbind(avg_steps,intervals))
plot(new$intervals,new$avg_steps,type = "l",xlab = "Intervals",
     ylab = "Average Steps",main = "Average Steps per Interval")
```
```{r=pa6,echo=TRUE}
index<-which.max(new$avg_steps)
max<-new[index,2]
```
```{r=pa7, echo=TRUE}
sum(is.na(activity$steps))
```
```{r=pa8,echo=TRUE}
index<-which(is.na(activity$steps))
l<-length(index)
steps_avg<-with(activity,tapply(steps,date,mean,na.rm=TRUE))
na<-mean(steps_avg,na.rm = TRUE)
for (i in 1:l) {
        activity[index[i],1]<-na
}
```
```{r=pa9,echo=TRUE}
sum(is.na(activity$steps))
str(activity)
```
```{r=pa10, echo=TRUE}
steps_2<-with(activity,tapply(steps,date,sum,na.rm=TRUE))
hist(steps_2,col = "green",xlab = "Total Steps",ylab = "Frequency",main = "Total Number of Steps per Day")
```
```{r=pa11,echo=TRUE}
print(mean_steps_2<-mean(steps_2))
print(median_steps_2<-median(steps_2))
```
```{r=pa12, echo=TRUE}
library(dplyr)
activity_mod<- mutate(activity, day = ifelse(weekdays(activity$date) == "Saturday" | weekdays(activity$date) == "Sunday", "weekend", "weekday"))
activity_mod$day<-as.factor(activity_mod$day)
str(activity_mod)
act_wknd<-subset(activity_mod,as.character(activity_mod$day)=="weekend")
act_wkdy<-subset(activity_mod,as.character(activity_mod$day)=="weekday")
steps_wknd<-with(act_wknd,tapply(steps,interval,mean,na.rm=TRUE))
steps_wkdy<-with(act_wkdy,tapply(steps,interval,mean,na.rm=TRUE))
int_wknd<-unique(act_wknd$interval)
int_wkdy<-unique(act_wkdy$interval)
new_wknd<-data.frame(cbind(steps_wknd,int_wknd))
new_wkdy<-data.frame(cbind(steps_wkdy,int_wkdy))
par(mfrow=c(2,1),mar=c(4,4,2,1))
plot(new_wknd$int_wknd,new_wknd$steps_wknd,type = "l",xlab = "Intervals",
     ylab = "Average Steps",main = "Weekend")
plot(new_wkdy$int_wkdy,new_wkdy$steps_wkdy,type = "l",xlab = "Intervals",
     ylab = "Average Steps",main = "Weekday")
```
